changelog:
  categories:
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Documentation and translations
      labels: [documentation, translation]
    - title: Other changes
      labels: ['*']
