package com.securepass.vault

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import org.json.JSONObject

internal data class GeneratorOptions(
    val length: Int = 20,
    val upper: Boolean = true,
    val lower: Boolean = true,
    val digits: Boolean = true,
    val symbols: Boolean = true,
) {
    val enabled: Boolean
        get() = upper || lower || digits || symbols

    fun request(): JSONObject =
        JSONObject()
            .put("length", length)
            .put("upper", upper)
            .put("lower", lower)
            .put("digits", digits)
            .put("symbols", symbols)
}

@Composable
internal fun PasswordGeneratorControls(vault: VaultRepository, t: (String, String) -> String) {
    var options by remember { mutableStateOf(GeneratorOptions()) }
    var generated by remember { mutableStateOf<Pair<GeneratorOptions, String>?>(null) }
    var revision by remember { mutableIntStateOf(0) }
    val value = generated?.takeIf { it.first == options && options.enabled }?.second.orEmpty()
    LaunchedEffect(options, revision) {
        generated = null
        if (options.enabled)
            try {
                val snapshot = options
                generated =
                    snapshot to vault.command("generate", snapshot.request()).getString("password")
            } catch (cancelled: kotlinx.coroutines.CancellationException) {
                throw cancelled
            } catch (_: Exception) {
                vault.report()
            }
    }
    Column(
        Modifier.heightIn(max = 560.dp).verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(8.dp),
    ) {
        Text(
            value.ifEmpty {
                if (options.enabled) t("正在生成…", "Generating…")
                else t("请至少选择一种字符类型", "Select at least one character type")
            },
            fontFamily = FontFamily.Monospace,
        )
        Text(t("长度：", "Length: ") + options.length)
        Slider(
            options.length.toFloat(),
            { options = options.copy(length = it.toInt()) },
            valueRange = 4f..64f,
            steps = 59,
            modifier = Modifier.semantics { contentDescription = t("密码长度", "Password length") },
        )
        listOf(
                Triple(t("大写字母", "Uppercase"), options.upper, "upper"),
                Triple(t("小写字母", "Lowercase"), options.lower, "lower"),
                Triple(t("数字", "Digits"), options.digits, "digits"),
                Triple(t("符号", "Symbols"), options.symbols, "symbols"),
            )
            .forEach { (label, checked, key) ->
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(label, Modifier.weight(1f))
                    Switch(
                        checked,
                        { enabled ->
                            options =
                                when (key) {
                                    "upper" -> options.copy(upper = enabled)
                                    "lower" -> options.copy(lower = enabled)
                                    "digits" -> options.copy(digits = enabled)
                                    else -> options.copy(symbols = enabled)
                                }
                        },
                        Modifier.semantics { contentDescription = label },
                    )
                }
            }
        Row {
            TextButton(onClick = { revision++ }, enabled = options.enabled) {
                Text(t("重新生成", "Regenerate"))
            }
            TextButton(onClick = { vault.copy(value) }, enabled = value.isNotEmpty()) {
                Text(t("复制", "Copy"))
            }
        }
    }
}
