//! Vectors generated by the actual legacy Dart cryptography package and VaultItem.toJson.
use serde_json::{json, Value};
use vault_core::{import_document, VaultSession};

const PASSWORD: &str = " Legacy fixture password! ";
const WEBDAV: &str = include_str!("fixtures/legacy/webdav-1.3.json");
const FIXED: &str = include_str!("fixtures/legacy/manual-2.0.json");
const SIMPLE: &str = include_str!("fixtures/legacy/manual-3.0.json");

#[test]
fn actual_dart_backups_restore_all_record_fields() {
    let expected: Value =
        serde_json::from_str(include_str!("fixtures/legacy/expected.json")).unwrap();
    for source in [WEBDAV, FIXED, SIMPLE] {
        let doc = import_document(source, PASSWORD, "json").unwrap();
        assert_eq!(doc.items.len(), 5);
        for original in expected["items"].as_array().unwrap() {
            let actual = doc
                .items
                .iter()
                .find(|i| i["id"] == original["id"])
                .unwrap();
            for (key, value) in original.as_object().unwrap() {
                assert_eq!(&actual[key], value, "Legacy field {key} must survive");
            }
        }
    }
}

#[test]
fn wrong_password_or_damaged_dart_backup_never_changes_existing_vault() {
    let directory = tempfile::tempdir().unwrap();
    let session = VaultSession::new(directory.path().to_string_lossy().into()).unwrap();
    let call = |value: Value| session.command(value.to_string());
    call(json!({"op":"create","password":"New native vault password!"})).unwrap();
    call(json!({"op":"save","item":{"id":"existing","type":"secureNote","title":"Keep me","note":"Existing native data"}})).unwrap();
    let before = call(json!({"op":"list"})).unwrap();
    assert!(
        call(json!({"op":"import","content":WEBDAV,"password":"Wrong legacy password"})).is_err()
    );
    assert_eq!(call(json!({"op":"list"})).unwrap(), before);
    let mut damaged: Value = serde_json::from_str(WEBDAV).unwrap();
    let mut payload = damaged["payload"].as_str().unwrap().to_owned();
    payload.replace_range(24..25, if &payload[24..25] == "A" { "B" } else { "A" });
    damaged["payload"] = json!(payload);
    assert!(
        call(json!({"op":"import","content":damaged.to_string(),"password":PASSWORD})).is_err()
    );
    assert_eq!(call(json!({"op":"list"})).unwrap(), before);
    let restored: Value = serde_json::from_str(
        &call(json!({"op":"import","content":WEBDAV,"password":PASSWORD})).unwrap(),
    )
    .unwrap();
    assert_eq!(restored["imported"], 5);
    call(json!({"op":"lock"})).unwrap();
    call(json!({"op":"unlock","password":"New native vault password!"})).unwrap();
    let doc: Value = serde_json::from_str(&call(json!({"op":"list"})).unwrap()).unwrap();
    assert_eq!(doc["items"].as_array().unwrap().len(), 6);
    assert_eq!(
        doc["items"]
            .as_array()
            .unwrap()
            .iter()
            .find(|i| i["id"] == "legacy-trash")
            .unwrap()["isDeleted"],
        true
    );
    let repeated: Value = serde_json::from_str(
        &call(json!({"op":"import","content":WEBDAV,"password":PASSWORD})).unwrap(),
    )
    .unwrap();
    assert_eq!(repeated["imported"], 0);
}
